services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5076:5076"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=postgres;Username=dbadmin;Password=x2y2z2G2B2
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=x2y2z2G2B2
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: